### ISSUE TITLE
Implementing position keys

### ISSUE THREAD

**Issue by PrometheusModding** [PrometheusSSE/SL-OStim-Conversion-Tool#10]
Coming up with a system that uses the animation classes and other parameters to determine positioning keys for animations

**Comment by Sairion350** [comment]
Quick note that might help, keys are seperated by ! to show which part is for which actor
So in Cy6!DDy6 you can immediately see this is an animation for 2 actors. Cy6 for the dom and DDy6 represents the sub. 
In a solo animation, there would only be one, so the entire key would be Cy6. For a 3p animations, we'd expect 3, so Cy6!DDy6!Cy9 or something similar!
