### ISSUE TITLE
Incorrect Animation Naming

### ISSUE THREAD

**Issue by OmniZenn** [PrometheusSSE/SL-OStim-Conversion-Tool#18]
How the tool names:
![image](https://user-images.githubusercontent.com/84869772/124519025-bde64e80-ddad-11eb-9c31-d7ed93bed597.png)

How animations are named in original OSex:
![image](https://user-images.githubusercontent.com/84869772/124519061-da828680-ddad-11eb-822a-ba58322154a9.png)

Notice how it's _**S0_0 and S0_1**_ instead of _**S1_1 to S2_1**_
The 0_0 and 0_1 is being skipped. It's also skipping S1_0 and going to S1_1 instead, then jumping to S2_1. I'm not actually sure if this would cause issues, but if possible it's probably better to stay consistent with the original OSex naming convention.

**Comment by PrometheusModding** [comment]
Thanks for the feedback wil be fixed in the next release.

**Comment by PrometheusModding** [comment]
![image](https://user-images.githubusercontent.com/79590942/124550082-705ef580-de30-11eb-9ac8-9893f1c03091.png)
Fixed
