### ISSUE TITLE
Animations in the FNIS.txt are being doubled & Path in the FNIS.txt is incorrect.

### ISSUE THREAD

**Issue by OmniZenn** [PrometheusSSE/SL-OStim-Conversion-Tool#20]
The actual animation names:
![image](https://user-images.githubusercontent.com/84869772/125855507-e40e795b-7a6e-450f-bf1f-975289b5a6f1.png)

The animation names in the FNIS.txt:
![image](https://user-images.githubusercontent.com/84869772/125855567-7bb566ff-b0cd-4b16-a9d4-cb5d0df5b0ed.png)

Here's a full default FNIS.txt created by the tool - this screenshot was taken from a different animation set I'm converting
(Note that the path is incorrect - it's missing the Set Name.) It should be: 
`0SA\mod\0Sex\anim\FLG\MIy9KNy6\Sx\FG_Reverse_Cowgirl1\`
![image](https://user-images.githubusercontent.com/84869772/126047136-ea9acf1e-73c0-4aea-96f1-ec6f5d7acf17.png)

The error(s) you get when generating the behavior:
![image](https://user-images.githubusercontent.com/84869772/125855739-80d18e06-086a-4908-bb00-04252835b73c.png)

**EDIT: After looking through some of the screenshots I noticed that all of the animations are there in the FNIS.txt - they're just being double and aren't in order like OSex. In the FG screenshot you can see all of the animations are listed twice.**

Here's the final FNIS.txt after editing it. You can see the list is shorter than the original:
![image](https://user-images.githubusercontent.com/84869772/126047849-422883f6-d11f-4527-9d7c-7367363d1a1c.png)

**[ENHANCEMENT]** If possible, would be nice to have the animations listed x_0, x_1, x_0, x_1, etc to stay as consistent with OSex as possible

**Comment by PrometheusModding** [comment]
May I suggest to rename the issue. I think the Paths in the FNIS are wrong not the animation names themself. Could You confirm that?
