### ISSUE TITLE
Original OSex animations are being copied 

### ISSUE THREAD

**Issue by OmniZenn** [PrometheusSSE/SL-OStim-Conversion-Tool#21]
When you follow the prompt when creating a New Animation Database in the tool, it copies all of OSex's original animations.

![image](https://user-images.githubusercontent.com/84869772/126029836-9a56b3d1-159f-4c8d-8b33-08f34f428c1b.png)

The prompt:
![image](https://user-images.githubusercontent.com/84869772/126029846-8e31433c-20d3-4d3f-884e-11d0798bd2ad.png)

This conflicts with the [Unofficial OSex Bug Patch](https://www.nexusmods.com/skyrimspecialedition/mods/47584) by Sairion and **causes the game to freeze when you start a scene**

**Comment by PrometheusModding** [comment]
I will fix this by including a preset file of the OSex Animations + Bug Fix in the tool.
If u want to solve this quickly, upon creation of new animationdatabase choose the scenes folder in your MO2 virtual directory
instead of the one from osex.
