### ISSUE TITLE
Only the first SL animation in a selection gets loaded in tool

### ISSUE THREAD

**Issue by daddydave-jpg** [PrometheusSSE/SL-OStim-Conversion-Tool#24]
If I select 8 animations, 4 for 1 actor and 4 for another, when it opens and I find it under tree on the left only the first animation in the list gets loaded.
![anim prop](https://user-images.githubusercontent.com/59400625/127700476-85e7a85a-03e8-4eb2-a7d1-7ddc4c0bf500.PNG)
![anim selec](https://user-images.githubusercontent.com/59400625/127700479-72e1b104-1cc2-4472-9891-1504904b62ea.PNG)

**Comment by PrometheusModding** [comment]
Fixed with v.0.9.7
