### ISSUE TITLE
Converted animations doesn't match the created Fnis animation list

### ISSUE THREAD

**Issue by OmniZenn** [PrometheusSSE/SL-OStim-Conversion-Tool#7]
The converted animations:
![image](https://user-images.githubusercontent.com/84869772/119710211-b8e3c600-be23-11eb-81a8-cddbeeb566f7.png)

The default Fnis animation list created by the tool:
![image](https://user-images.githubusercontent.com/84869772/119712021-c7cb7800-be25-11eb-9542-34cc85829c18.png)

What it should be:
![image](https://user-images.githubusercontent.com/84869772/119710761-5ccd7180-be24-11eb-8677-0b5d9b2797ad.png)

**Comment by PrometheusModding** [comment]
Will look into that fix will release with next minor update .
